// <auto-generated />
using GoDAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GoDAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210610052444_primera")]
    partial class primera
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GoDAPI.Models.Battle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("MoveOne")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MoveTwo")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Battles");
                });

            modelBuilder.Entity("GoDAPI.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("POne")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PTwo")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ScoreOne")
                        .HasColumnType("int");

                    b.Property<int>("ScoreTwo")
                        .HasColumnType("int");

                    b.Property<string>("Winner")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GoDAPI.Models.Battle", b =>
                {
                    b.HasOne("GoDAPI.Models.Game", null)
                        .WithMany("Battles")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
